language: java

jdk:
- openjdk8

sudo: enabled

before_install:
  - chmod +x mvnw

# git strips the wrapper jar file so we have to force its download during the build
install:
   - ./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
   - ./mvnw test -B